# Generated by Django 3.1.2 on 2020-10-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='create_date',
            field=models.DateField(default='2020-10-21'),
        ),
        migrations.AlterField(
            model_name='propusk',
            name='proverka_date',
            field=models.DateField(default='2020-10-21'),
        ),
    ]
