# Generated by Django 3.1.2 on 2020-10-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propusk',
            name='annul_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
