# Generated by Django 3.1.2 on 2020-10-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201021_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='create_date',
            field=models.DateField(default='2020-10-25'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permission_type',
            field=models.CharField(choices=[('NOTHING', 'Не определен'), ('SUPER', 'Создатель'), ('NO_LIMITS', 'Без ограничений'), ('PRODUCTION', 'Всё производство'), ('PRODUCTION_WORKER', 'Производство'), ('CLIENT_WORKER', 'Работа с Клиентами'), ('SALE_WORKER', 'Отдел продаж')], default=0, max_length=17),
        ),
        migrations.AlterField(
            model_name='propusk',
            name='proverka_date',
            field=models.DateField(default='2020-10-25'),
        ),
        migrations.AlterField(
            model_name='propusk',
            name='serial_type',
            field=models.CharField(blank=True, choices=[('', ''), ('ББ', 'ББ'), ('БА', 'БА')], default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='propusk',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('Активен', 'Активен'), ('Закончился', 'Закончился'), ('Аннулирован', 'Аннулирован')], default='', max_length=12, null=True),
        ),
    ]
