# Generated by Django 3.1.2 on 2020-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201025_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='propusk',
            name='zone_type',
            field=models.CharField(blank=True, choices=[('', ''), ('МКАД', 'МКАД'), ('ТТК', 'ТТК'), ('СК', 'СК')], default='', max_length=4, null=True),
        ),
    ]
